Repository requests-cache/requests-cache, pull requests merged in 2021-06, with the labels that each got.

#277 Remove data in "ignored_parameters" from cached requests
  docs/user_guide.rst
  poetry.lock
  pyproject.toml
  requests_cache/backends/base.py
  requests_cache/cache_keys.py
  tests/conftest.py
  tests/integration/base_cache_test.py
  tests/performance_test.py
Labels: enhancement

#282 Add Dependabot V2 config, more pre-commit hooks, and update dev dependencies
  .github/dependabot.yml
  .github/pre-commit.yml
  .github/workflows/build.yml
  docs/conf.py
  poetry.lock
  pyproject.toml
Labels: logistics

#275 Refactor serializers into separate classes, and add JSON and BSON serializers
  .github/workflows/build.yml
  CONTRIBUTING.md
  HISTORY.md
  docs/advanced_usage.rst
  docs/sample_response.json
  docs/user_guide.rst
  examples/performance_test.py
  poetry.lock
  pyproject.toml
  requests_cache/__init__.py
  requests_cache/backends/__init__.py
  requests_cache/backends/base.py
  requests_cache/backends/dynamodb.py
  requests_cache/backends/filesystem.py
  requests_cache/backends/gridfs.py
  requests_cache/backends/mongo.py
  requests_cache/backends/redis.py
  requests_cache/backends/sqlite.py
  requests_cache/cache_keys.py
  requests_cache/models/request.py
  requests_cache/models/response.py
  requests_cache/serializers/__init__.py
  requests_cache/serializers/base.py
  requests_cache/serializers/bson_serializer.py
  requests_cache/serializers/json_serializer.py
  requests_cache/serializers/pickle.py
  requests_cache/serializers/pickle_serializer.py
  runtests.sh
  tests/integration/base_cache_test.py
  tests/integration/base_storage_test.py
  tests/unit/test_serializers.py
  tests/unit/test_session.py
Labels: enhancement

#297 Add automated tests for cache behavior after version upgrades
  tests/conftest.py
  tests/generate_test_db.py
  tests/integration/test_compat.py
  tests/performance_test.py
  tests/sample_data/sample.db.0.3.0
  tests/sample_data/sample.db.0.4.0
  tests/sample_data/sample.db.0.4.13
  tests/sample_data/sample.db.0.5.0
  tests/sample_data/sample.db.0.5.1
  tests/sample_data/sample.db.0.5.2
  tests/sample_data/sample.db.0.6.0
  tests/sample_data/sample.db.0.6.1
  tests/sample_data/sample.db.0.6.2
  tests/sample_data/sample.db.0.6.3
  tests/sample_data/sample.db.0.6.4
  tests/sample_data/sample.db.0.7.0
Labels: bug, tests
