Repository requests-cache/requests-cache, pull requests merged in 2021-03, with the labels that each got.

#178 Migrate builds from Travis CI to GitHub Actions
  .github/pre-commit.yml
  .github/workflows/build.yml
  .travis.yml
  requests_cache/backends/storage/gridfspickledict.py
  requirements-test.txt
  setup.py
  tests/test_dynamodbdict.py
Labels: logistics

#180 Add GitHub Actions config for automated pypi releases
  .github/workflows/build.yml
  setup.py
Labels: logistics

#181 Documentation improvements
  .readthedocs.yml
  CONTRIBUTING.md
  README.md
  README.rst
  docker-compose.yml
  docs/conf.py
  requests_cache/__init__.py
  requests_cache/core.py
  setup.py
Labels: documentation, logistics

#183 Refactor CachedSession to be usable as a mixin class
  docs/user_guide.rst
  requests_cache/__init__.py
  requests_cache/backends/__init__.py
  requests_cache/backends/base.py
  requests_cache/backends/dynamodb.py
  requests_cache/backends/gridfs.py
  requests_cache/backends/mongo.py
  requests_cache/backends/redis.py
  requests_cache/backends/sqlite.py
  requests_cache/backends/storage/dbdict.py
  requests_cache/backends/storage/mongodict.py
  requests_cache/core.py
  setup.py
  tests/__init__.py
  tests/test_monkey_patch.py
Labels: bug, enhancement

#177 Add individual expire_after per request.
  CONTRIBUTORS.rst
  README.md
  docs/api.rst
  docs/conf.py
  docs/user_guide.rst
  example_request.py
  requests_cache/__init__.py
  requests_cache/backends/base.py
  requests_cache/core.py
  tests/test_cache.py
  tests/test_dbdict.py
  tests/test_expiration_datetime.py
  tests/test_monkey_patch.py
  tests/test_per_request_cache.py
  tests/test_thread_safety.py
Labels: enhancement

#189 Refactor cached response info & initialization into a separate class
  example_request.py
  pyproject.toml
  requests_cache/__init__.py
  requests_cache/backends/__init__.py
  requests_cache/backends/base.py
  requests_cache/core.py
  requests_cache/response.py
  setup.cfg
  setup.py
  tests/conftest.py
  tests/test_cache.py
  tests/test_expiration_datetime.py
  tests/test_monkey_patch.py
  tests/test_per_request_cache.py
  tests/test_response.py
Labels: documentation, enhancement

#193 Add support for setting different expiration times based on URL patterns
  requests_cache/core.py
  tests/test_cache.py
Labels: enhancement

#195 Add property to get all URLs in the cache
  requests_cache/backends/base.py
  requests_cache/backends/dynamodb.py
  requests_cache/backends/gridfs.py
  requests_cache/backends/mongo.py
  requests_cache/backends/redis.py
  requests_cache/backends/sqlite.py
  tests/test_cache.py
Labels: enhancement

#196 Add optional integration with itsdangerous for safer serialization
  .github/workflows/build.yml
  docker-compose.yml
  requests_cache/backends/__init__.py
  requests_cache/backends/base.py
  requests_cache/backends/dynamodb.py
  requests_cache/backends/gridfs.py
  requests_cache/backends/mongo.py
  requests_cache/backends/redis.py
  requests_cache/backends/sqlite.py
  requests_cache/backends/storage/__init__.py
  requests_cache/backends/storage/dbdict.py
  requests_cache/backends/storage/dynamodbdict.py
  requests_cache/backends/storage/gridfspickledict.py
  requests_cache/backends/storage/mongodict.py
  requests_cache/backends/storage/redisdict.py
  requests_cache/core.py
  setup.py
  tests/test_cache.py
  tests/test_custom_dict.py
  tests/test_dbdict.py
  tests/test_dynamodbdict.py
  tests/test_gridfsdict.py
  tests/test_mongodict.py
  tests/test_redisdict.py
Labels: enhancement

#191 More usage examples, formatting, and editing for Readme + Sphinx docs
  CONTRIBUTING.md
  HISTORY.md
  HISTORY.rst
  README.md
  docs/advanced_usage.rst
  docs/api.rst
  docs/conf.py
  docs/contributing.rst
  docs/history.rst
  docs/index.rst
  docs/user_guide.rst
  example.py
  example_request.py
  examples/basic_usage.py
  examples/expiration.py
  examples/session_patch.py
  pyproject.toml
  setup.cfg
Labels: documentation

#199 Expose timeout parameter for SQLite backend
  requests_cache/backends/sqlite.py
  tests/test_dbdict.py
Labels: enhancement

#203 Update 'Security' docs and add a warning when using plain pickle with some backends
  README.md
  docs/advanced_usage.rst
  docs/conf.py
  docs/index.rst
  docs/security.rst
  examples/README.md
  requests_cache/backends/base.py
  requests_cache/backends/sqlite.py
  setup.py
Labels: documentation

#204 Add logging to main cache operations
  docs/advanced_usage.rst
  docs/api.rst
  docs/index.rst
  docs/user_guide.rst
  requests_cache/__init__.py
  requests_cache/backends/__init__.py
  requests_cache/backends/base.py
  requests_cache/backends/sqlite.py
  requests_cache/core.py
  requests_cache/response.py
  tests/test_cache.py
  tests/test_dbdict.py
Labels: documentation, logistics

#206 Update remove_expired_responses() to also remove invalid responses
  HISTORY.md
  requests_cache/backends/__init__.py
  requests_cache/backends/base.py
  tests/conftest.py
  tests/test_cache.py
Labels: bug, enhancement

#197 Improve request normalization for generating cache keys
  HISTORY.md
  requests_cache/backends/__init__.py
  requests_cache/backends/base.py
  requests_cache/cache_keys.py
  requests_cache/core.py
  setup.py
  tests/test_cache.py
Labels: bug, enhancement
