Repository requests-cache/requests-cache, pull requests merged in 2021-02, with the labels that each got.

#85 Avoiding iteration error when using BaseCache from multiple threads
  requests_cache/backends/base.py
Labels: bug

#172 Temporarily skip tests that depend on httpbin.org/redirect endpoints
  tests/test_cache.py
Labels: bug

#176 Return date of cached response
  requests_cache/core.py
  tests/test_cache.py
Labels: enhancement

#173 Drop support for python <= 3.5 and related code cleanup
  .gitignore
  .travis.yml
  HISTORY.rst
  docs/conf.py
  example.py
  pyproject.toml
  requests_cache/__init__.py
  requests_cache/backends/__init__.py
  requests_cache/backends/base.py
  requests_cache/backends/dynamodb.py
  requests_cache/backends/gridfs.py
  requests_cache/backends/mongo.py
  requests_cache/backends/redis.py
  requests_cache/backends/sqlite.py
  requests_cache/backends/storage/dbdict.py
  requests_cache/backends/storage/dynamodbdict.py
  requests_cache/backends/storage/gridfspickledict.py
  requests_cache/backends/storage/mongodict.py
  requests_cache/backends/storage/redisdict.py
  requests_cache/compat.py
  requests_cache/core.py
  requirements-test.txt
  sandbox.py
  setup.cfg
  setup.py
  tests/__init__.py
  tests/test_cache.py
  tests/test_custom_dict.py
  tests/test_dbdict.py
  tests/test_dynamodbdict.py
  tests/test_gridfsdict.py
  tests/test_mongodict.py
  tests/test_monkey_patch.py
  tests/test_redisdict.py
  tests/test_thread_safety.py
Labels: logistics
