Repository requests-cache/requests-cache, pull requests merged in 2021-04, with the labels that each got.

#208 More improvements for unit tests and CI
  .github/workflows/build.yml
  CONTRIBUTING.md
  docker-compose.yml
  requests_cache/backends/base.py
  requests_cache/cache_keys.py
  requests_cache/core.py
  requests_cache/response.py
  setup.py
  tests/README.md
  tests/conftest.py
  tests/integration/__init__.py
  tests/integration/test_backends.py
  tests/integration/test_cache.py
  tests/integration/test_dynamodb.py
  tests/integration/test_gridfs.py
  tests/integration/test_mongodb.py
  tests/integration/test_redis.py
  tests/integration/test_sqlite.py
  tests/test_monkey_patch.py
  tests/test_thread_safety.py
  tests/unit/test_cache.py
  tests/unit/test_monkey_patch.py
  tests/unit/test_response.py
  tests/unit/test_thread_safety.py
Labels: enhancement, logistics

#211 Use pytest-xdist to parallelize unit tests
  .github/workflows/build.yml
  CONTRIBUTING.md
  runtests.sh
  setup.py
  tests/unit/test_thread_safety.py
Labels: documentation, logistics, tests

#216 Split up 'core' into smaller modules
  .github/workflows/build.yml
  README.md
  docs/api.rst
  requests_cache/__init__.py
  requests_cache/core.py
  requests_cache/patcher.py
  requests_cache/session.py
  runtests.sh
  tests/conftest.py
  tests/unit/test_cache.py
  tests/unit/test_patcher.py
Labels: logistics

#217 Reorganize user guide sections, and add auto-generated rst sources with sphinx-apidoc
  CONTRIBUTING.md
  CONTRIBUTORS.md
  HISTORY.md
  README.md
  docs/Makefile
  docs/advanced_usage.rst
  docs/api.rst
  docs/conf.py
  docs/contributing.rst
  docs/contributors.rst
  docs/index.rst
  docs/related_projects.rst
  docs/security.rst
  docs/user_guide.rst
  requests_cache/backends/base.py
  requests_cache/backends/dynamodb.py
  requests_cache/backends/sqlite.py
  requests_cache/patcher.py
  requests_cache/response.py
  requests_cache/session.py
  tests/unit/test_cache.py
Labels: documentation

#219 Some more documentation edits and readthedocs container config
  CONTRIBUTING.md
  HISTORY.md
  docker-compose.yml
  docs/Dockerfile
  docs/advanced_usage.rst
  docs/user_guide.rst
Labels: documentation

#225 Handle errors due to invalid responses in BaseCache.urls
  HISTORY.md
  docs/advanced_usage.rst
  requests_cache/__init__.py
  requests_cache/backends/__init__.py
  requests_cache/backends/base.py
  requests_cache/patcher.py
  requests_cache/response.py
  requests_cache/session.py
  tests/unit/test_cache.py
Labels: bug

#227 Add optional support for pytest-httpbin
  CONTRIBUTING.md
  tests/conftest.py
  tests/integration/test_cache.py
Labels: tests

#228 Add & update backend integration tests
  HISTORY.md
  requests_cache/backends/__init__.py
  requests_cache/backends/dynamodb.py
  requests_cache/backends/gridfs.py
  setup.py
  tests/conftest.py
  tests/integration/test_backends.py
  tests/integration/test_dynamodb.py
  tests/integration/test_gridfs.py
  tests/integration/test_mongodb.py
  tests/integration/test_redis.py
  tests/integration/test_sqlite.py
Labels: tests

#231 Include example scripts on readthedocs
  docs/_static/collapsible_container.css
  docs/_templates/page.html
  docs/conf.py
  docs/examples.rst
  docs/index.rst
  docs/related_projects.rst
  examples/README.md
  examples/basic_usage.py
  examples/convert_cache.py
  examples/expiration.py
  examples/log_requests.py
  examples/session_patch.py
Labels: documentation

#234 Fix handling of decode_content parameter for raw.read(...)
  requests_cache/response.py
  tests/integration/test_cache.py
  tests/unit/test_response.py
Labels: bug, enhancement

#237 Allow passing any valid backend connection kwargs via BaseCache
  docs/conf.py
  requests_cache/backends/__init__.py
  requests_cache/backends/base.py
  requests_cache/backends/dynamodb.py
  requests_cache/backends/gridfs.py
  requests_cache/backends/mongo.py
  requests_cache/backends/redis.py
  requests_cache/backends/sqlite.py
  requests_cache/session.py
  tests/integration/test_dynamodb.py
  tests/integration/test_gridfs.py
  tests/integration/test_mongodb.py
  tests/integration/test_redis.py
  tests/integration/test_sqlite.py
Labels: enhancement

#239 Run multi-threaded tests for all backends
  .github/workflows/build.yml
  HISTORY.md
  requests_cache/backends/dynamodb.py
  runtests.sh
  tests/conftest.py
  tests/integration/test_backends.py
  tests/integration/test_dynamodb.py
  tests/integration/test_thread_safety.py
  tests/unit/test_thread_safety.py
Labels: tests

#238 Add a filesystem backend
  .gitignore
  CONTRIBUTORS.md
  HISTORY.md
  README.md
  docs/user_guide.rst
  pyproject.toml
  requests_cache/__init__.py
  requests_cache/backends/__init__.py
  requests_cache/backends/filesystem.py
  requests_cache/backends/sqlite.py
  tests/integration/test_backends.py
  tests/integration/test_filesystem.py
  tests/integration/test_thread_safety.py
Labels: enhancement

#242 Refactor backend integration tests
  requests_cache/backends/base.py
  requests_cache/backends/dynamodb.py
  requests_cache/backends/filesystem.py
  requests_cache/backends/gridfs.py
  requests_cache/backends/mongo.py
  requests_cache/backends/redis.py
  requests_cache/backends/sqlite.py
  runtests.sh
  tests/conftest.py
  tests/integration/test_backends.py
  tests/integration/test_dynamodb.py
  tests/integration/test_filesystem.py
  tests/integration/test_gridfs.py
  tests/integration/test_mongodb.py
  tests/integration/test_redis.py
  tests/integration/test_sqlite.py
  tests/integration/test_thread_safety.py
Labels: tests

#253 Add some more convenience methods for getting cache info
  HISTORY.md
  docs/advanced_usage.rst
  requests_cache/backends/base.py
  requests_cache/backends/mongo.py
  requests_cache/backends/sqlite.py
  requests_cache/response.py
  setup.py
  tests/unit/test_cache.py
  tests/unit/test_response.py
Labels: enhancement

#255 Add support for bypassing the cache if expire_after=0
  HISTORY.md
  docs/user_guide.rst
  requests_cache/response.py
  requests_cache/session.py
  tests/unit/test_cache.py
  tests/unit/test_patcher.py
  tests/unit/test_response.py
Labels: enhancement

#256 Add support for caching multipart file uploads
  CONTRIBUTORS.md
  HISTORY.md
  requests_cache/session.py
  tests/integration/base_cache_test.py
Labels: bug, enhancement
