Repository requests-cache/requests-cache, pull requests merged in 2022-10, with the labels that each got.

#708 Explicitly disable pickling CachedSession objects
  HISTORY.md
  requests_cache/session.py
  tests/unit/test_session.py
Labels: bug

#709 Add support for header values as bytes
  HISTORY.md
  requests_cache/policy/directives.py
  tests/unit/policy/test_actions.py
Labels: bug, enhancement

#712 Minor backwards compatibility changes
  HISTORY.md
  requests_cache/backends/base.py
  requests_cache/backends/sqlite.py
  requests_cache/session.py
  tests/compat/test_requests_mock_load_cache.py
  tests/compat/test_responses_load_cache.py
  tests/unit/test_base_cache.py
Labels: bug, docs

#710 Add forwards-compatibility and some DeprecationWarnings for some upcoming changes between 0.9 and 1.0
  HISTORY.md
  requests_cache/__init__.py
  requests_cache/backends/__init__.py
  requests_cache/backends/base.py
  requests_cache/cache_control.py
  requests_cache/models/response.py
  requests_cache/patcher.py
  requests_cache/policy/__init__.py
  requests_cache/policy/actions.py
  requests_cache/session.py
  tests/unit/policy/test_actions.py
Labels: enhancement

#718 Typo
  docs/user_guide/backends/filesystem.md
Labels: docs

#720 Handle using a converter that doesn't support `omit_if_default`
  requests_cache/serializers/cattrs.py
  tests/unit/test_serializers.py
Labels: bug, dependencies
