Repository requests-cache/requests-cache, pull requests merged in 2022-02, with the labels that each got.

#517 Skip empty body decode/encode in normalize_json_body
  requests_cache/cache_keys.py
Labels: enhancement

#527 Fix disabling expiration for a single request
  .all-contributorsrc
  CONTRIBUTORS.md
  HISTORY.md
  docs/user_guide/expiration.md
  requests_cache/cache_control.py
  tests/unit/test_session.py
Labels: bug

#529 Fix serialization in filesystem backend with binary content that is also valid UTF-8
  .all-contributorsrc
  CONTRIBUTORS.md
  HISTORY.md
  docs/user_guide/serializers.md
  requests_cache/backends/filesystem.py
  requests_cache/serializers/pipeline.py
  requests_cache/serializers/preconf.py
  tests/integration/test_filesystem.py
  tests/unit/test_serializers.py
Labels: bug, serialization

#530 Fix handling BSON serializer differences between pymongo's bson and standalone bson codec
  HISTORY.md
  pyproject.toml
  requests_cache/serializers/preconf.py
  tests/integration/test_filesystem.py
Labels: bug

#538 Fix request normalization for request body with a list as a JSON root
  HISTORY.md
  requests_cache/cache_keys.py
  tests/unit/test_cache_keys.py
Labels: bug

#540 Skip normalizing an excessively large JSON request body due to performance impact
  HISTORY.md
  requests_cache/cache_keys.py
  tests/unit/test_cache_keys.py
Labels: enhancement, performance

#537 Fix some thread safety issues and improve concurrency tests
  .github/workflows/deploy.yml
  HISTORY.md
  noxfile.py
  poetry.lock
  requests_cache/backends/filesystem.py
  requests_cache/backends/gridfs.py
  requests_cache/backends/sqlite.py
  tests/conftest.py
  tests/integration/base_cache_test.py
  tests/integration/test_mongodb.py
Labels: bug, tests, performance
