Repository requests-cache/requests-cache, pull requests merged in 2023-11, with the labels that each got.

#896 Change httpx-cache to Hishel
  docs/project_info/related_projects.md
Labels: docs

#900 Handle corner case with streaming requests, conditional requests, and redirects
  .github/workflows/build.yml
  HISTORY.md
  requests_cache/models/response.py
  requests_cache/policy/settings.py
  requests_cache/session.py
  tests/unit/models/test_response.py
  tests/unit/test_patcher.py
  tests/unit/test_session.py
Labels: bug

#901 Update `redact_reponse()` to filter details without normalizing
  HISTORY.md
  requests_cache/cache_keys.py
  requests_cache/models/raw_response.py
  tests/unit/models/test_raw_response.py
  tests/unit/test_cache_keys.py
Labels: bug

#902 Add support for HTTP method override headers
  HISTORY.md
  docs/user_guide/filtering.md
  requests_cache/cache_keys.py
  requests_cache/policy/actions.py
  requests_cache/policy/directives.py
  tests/unit/test_session.py
Labels: enhancement

#908 Fix for compatibility with cattrs 23.2
  HISTORY.md
  poetry.lock
  requests_cache/models/response.py
  requests_cache/serializers/cattrs.py
  requests_cache/serializers/preconf.py
  tests/benchmark_serializers.py
  tests/conftest.py
  tests/integration/base_cache_test.py
  tests/unit/test_serializers.py
Labels: bug
