Repository requests-cache/requests-cache, pull requests merged in 2023-03, with the labels that each got.

#804 Allow regexes for URL expiration patterns
  HISTORY.md
  docs/user_guide/expiration.md
  requests_cache/policy/__init__.py
  requests_cache/policy/expiration.py
  requests_cache/policy/settings.py
  tests/unit/policy/test_expiration.py
Labels: enhancement

#806 Use time-machine instead of sleep for timing-based tests
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/unit/test_base_cache.py
  tests/unit/test_session.py
Labels: tests

#810 Don't normalize CachedResponse.url when redacting ignored params
  HISTORY.md
  requests_cache/cache_keys.py
  tests/unit/test_cache_keys.py
Labels: bug
