Repository requests-cache/requests-cache, pull requests merged in 2024-12, with the labels that each got.

#1035 Add `autoclose` option to close backend connections when the session is closed
  HISTORY.md
  requests_cache/patcher.py
  requests_cache/policy/settings.py
  requests_cache/session.py
  tests/unit/test_patcher.py
  tests/unit/test_session.py
Labels: bug, enhancement

#1029 Fix request headers sent when `expire_after` is set to `DO_NOT_CACHE`
  HISTORY.md
  requests_cache/policy/actions.py
  requests_cache/policy/directives.py
  requests_cache/policy/expiration.py
  tests/unit/policy/test_expiration.py
  tests/unit/test_session.py
Labels: bug

#1037 add tip/warning for header variation on cache hits
  docs/user_guide/expiration.md
  docs/user_guide/matching.md
Labels: docs
